### ISSUE TITLE
Lab 3: is my logic correct?

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#10]
To calculate gauss curvature, I have the following code (very simple and straightforward I think):

(code removed)

But I got a completely different result:
<img width="378" alt="2016-10-12 8 36 37" src="https://cloud.githubusercontent.com/assets/9297940/19335889/a339efc2-90bb-11e6-8e56-f6474e676c93.png">

What could be the problem?

**Comment by xuzheng0927** [comment]
I found an issue that the acos function's value actually ranges from -pi/2 to pi/2. I fixed this but still get a result different from the solution. What could be the problem??

<img width="351" alt="2016-10-12 10 02 16" src="https://cloud.githubusercontent.com/assets/9297940/19337191/9004da78-90c7-11e6-9823-94534ea2b20a.png">

**Comment by nlguillemot** [comment]
I tried to illustrate what the variables in your code correspond to. You can see the angle is in the wrong corner.

![http://i.imgur.com/TMYbyKd.png](http://i.imgur.com/TMYbyKd.png)

**Comment by nlguillemot** [comment]
Also I've removed your code from your post to prevent others from copying it, just to be safe.

**Comment by xuzheng0927** [comment]
I see. I thought the vertex associated with a half edge was the "point-to" one but actually it is the "point-from" one. Now it is correct.
