### ISSUE TITLE
How to detect an "invalid collapse"?

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#11]
This is from the assignment description: "Invalid collapses are defined as the ones that produce a non-manifold configuration (or a face fold-over)." For the face fold-over, we can use the threshold provided by the base code (min_cost). What about the "non-manifold configuration"? Any rules (or do we need to deduct the rules ourselves)?

**Comment by taiya** [comment]
Check the SurfaceMesh API ;)

**Comment by nlguillemot** [comment]
There's also some discussion about this in the polygon mesh processing textbook.

**Comment by xuzheng0927** [comment]
I found an "is_manifold" function. So how do we "simulate" the collapse? I plan is to associate all vertex v0's half edges with the v1 (the one to be collapsed into) and remove v0, then check whether it is valid. If not I'll create v0 and associate those half edges back. But it seems it is not "simulation".

**Comment by xuzheng0927** [comment]
Solved and will closed the issue.
