### ISSUE TITLE
Found a mistake in the white board notes..

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#12]
"D_ii=0 if i belongs to the constraints; 0 otherwise"
I think should be "D_ii=1..."
That's why my output was always incorrect :(

**Comment by xuzheng0927** [comment]
@ataiya By the way, is the "re-ordering method" the one that uses matrix A=[A11,A12;A21,A22]?

**Comment by taiya** [comment]
Thanks for the report!
I will write my digital notes and upload it to the Dropbox folder this afternoon.

**Comment by taiya** [comment]
And yes, the re-ordering method (i.e. hard constraints) is when you first permute the matrices, and then you solve only for the variables that are not constrained
