### ISSUE TITLE
HW2 - Link problem

### ISSUE THREAD

**Issue by maurizio-kovacic** [ataiya/dgp#14]
I don't know if I'm doing it right or not.
Links to Geomorph video and reference [4] pdf redirect to dgp wiki.

**Comment by taiya** [comment]
Should be fixed

**Comment by maurizio-kovacic** [comment]
For me the video is corrupted. (Any one else same problem?)
Suggestion: change it into 
https://www.youtube.com/watch?v=UCLCkP32va8

[4] still links to dgp wiki
