### ISSUE TITLE
The "Eigen::SimplicialCholesky"??

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#17]
I've been tortured by the poor documentation of eigen library so much. How to get the decomposed matrix L after running solver.compute(L_uu)? I tried `auto new_p = solver.compute(L_uu)` but doesn't work at all. There is not any example I can find.

**Comment by taiya** [comment]
You don't need to "extract" the matrix from the factorizer.
You simply call a solve method from the factorizer class (not RHS stands for right hand side):
https://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialCholesky.html

(this does the back-substitution in a way that is "factorizer-aware")

**Comment by xuzheng0927** [comment]
Got that. Thanks a lot!

My code base still cannot be compiled by cmake (there's a confusing error "ld: 17 duplicate symbols for architecture x86_64") so I cannot do any debugging right now. I might need some help the next week after class :(

**Comment by taiya** [comment]
Pull the code, I've pushed an update this morning that should fix the problem! A 2nd fix might be necessary to draw handles, but for now it should compile.

**Comment by xuzheng0927** [comment]
Great, it works. I'll continue my work :)
