### ISSUE TITLE
The coordinate of click is not correctly returned

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#18]
The pos returned from function "unproject_mouse" is not consistent with the mesh coordinate.

I tried printing `xPos, yPos, _width, _height` after I clicked the right bottom corner, and I got:

`xPos: 326.086,
 yPos: 325.675,
width: 800, 
height: 800`

I am using Mac. Anybody has an idea why this happens?

**Comment by taiya** [comment]
The trace code is meant to be run on the lab. I assume your mac might have a retina screen?
If you want to use your laptop, you'll have to apply a correction to re-scale it properly.

I think I had this fixed it for the generic trackball window, see this code:
OpenGP::TrackballWindow::mouse_move_callback(double x_window, double y_window)

**Comment by xuzheng0927** [comment]
I see that.. what a headache

**Comment by taiya** [comment]
Unfortunately there is no way for the TA to help you, as he doesn't have a Mac+Retina computer available for testing :\

**Comment by xuzheng0927** [comment]
I might be able to re-scale it when dealing with the 2D grid, but the 3D grid should be difficult for me (how to get the z coordinate value?) Anyway I cannot spend too much time on this. If the code works on the computers in the lab, I may have to spend most of my time in the lab.
