### ISSUE TITLE
OpenGP always exist at the bottom of the window

### ISSUE THREAD

**Issue by shengyangwei** [ataiya/dgp#2]
<img width="1159" alt="screen shot 2016-01-21 at 6 13 40 pm" src="https://cloud.githubusercontent.com/assets/16831840/12524763/4cc08c18-c114-11e5-8be9-3f15cf10f5d5.png">

(NOTE) this only happens with **retina** displays in OSX.

**Comment by ataiya** [comment]
@marovira wasn't this fixed in the arcball code?

**Comment by marovira** [comment]
@ataiya yes, I just forgot to push the change. It is fixed now.

**Comment by ataiya** [comment]
(Starting tomorrow) this will be fixed by manually flipping the "retina_display" boolean in GlfwWindow. 
However, I cannot see a way of checking whether I am on a retina display or not, so I am failing to see a more elegant solution.

@marovira pull the change from dgp-private before the lab

**Comment by ataiya** [comment]
@marovira finally found the fix (also ranted at the glfw guys to mention it a bit better). Import the new copy of OpenGP and you will find it in there.
