### ISSUE TITLE
Is the given data obj correct?

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#22]
I am looking at the very simple quad_mesh object and found something weird. In the picture, when calculating cotan values of vertex i, the vertex of angle beta acquired by using mesh.to_vertex(mesh.next_halfedge(e_ij)) is on the upper-left corner, which does not have an edge connected to vertex i at all. That makes it impossible to get the right laplacian beltrami matrix. The woody object is too big to check, so is it possible this data file also has the same issue?

![2016-11-17 10 00 01](https://cloud.githubusercontent.com/assets/9297940/20420409/7786328c-ad12-11e6-8f40-4eac9499cd9a.jpg)

**Comment by nlguillemot** [comment]
I manually consulted the meshed_quad.obj file, and the obj file itself doesn't look wrong.

**Comment by xuzheng0927** [comment]
So for every half edge of vertex i, the vertices alpha and beta should be connected to vertex i, right? But I got the following output:

calculating vertex 0
p_i: 0.5,-0.5,0
p_j: -0.5-0.5,0
p_b: -0.5,0.5,0
p_a: 0,0,0

There is no edge between p_i and p_b. What could be wrong? Toooo confused.

**Comment by xuzheng0927** [comment]
I used the mesh_laplacian_cotangent.m in Dropbox and got this result (same as my manual calculation):

-2,0,0,0,2
0,-2,0,0,2
0,0,-2,0,2
0,0,0,-2,2
2,2,2,2,-8

The result got from the github code (should be wrong because vertex 0~4 only have 3 edges):

-4 1 0 1 2 
1 -4 1 0 2 
0 1 -4 1 2 
1 0 1 -4 2 
2 2 2 2 -8

Is it possible that the mesh.next_halfedge function has something wrong?

**Comment by nlguillemot** [comment]
It would be really really weird if `mesh.next_halfedge` had a bug since it's been used for so long.

**Comment by xuzheng0927** [comment]
Ok, then I'll need to write a function not using mesh.next_halfedge and see
if the result can be different.
