### ISSUE TITLE
Question: Laplacian weight matrix

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#25]
In hw3 part 2, I tried using Laplacian-Beltrami weight matrix WITHOUT 1/(2*A_i) coefficients, and it gave me the correct output (the original function in the code base uses the area coefficients, with which I always got exploding points).

I also noticed that in ARAP, the weight is without 1/(2*A_i) as well. Should that be removed?

**Comment by nlguillemot** [comment]
That might be the trick. I wonder why that is.

**Comment by taiya** [comment]
1) biharmonic deformation: you are using a SPD (symmetric positive definite) factorizer. Is your system matrix SPD? (potentially not) The slides (fairing) and the book's appendix cover how to correct this.
2) ARAP: _carefully_ read the end of Sec. 2 in the paper

**Comment by xuzheng0927** [comment]
My ARAP is working good now. I'll check (1) this evening.

**Comment by taiya** [comment]
@xuzheng0927  before closing can you confirm what I was saying above addressed your problems?

**Comment by xuzheng0927** [comment]
I can confirm that my problem is due to using a non-SPD matrix. But I
haven't got the SPD implemented in my code (will do probably after the
exam).
