### ISSUE TITLE
Time-Coded Light Patterns

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#26]
Is there an example explaining how this works? I'm reading the slides but it only has this brief description:

Assign each stripe a unique light code
– Project several b/w patterns over time
– Color pattern identifies row/column

**Comment by taiya** [comment]
(See Fig.4)
https://www.osapublishing.org/DirectPDFAccess/366A1CC7-ADF3-DE15-B5C9EE443A0CF17E_211561/aop-3-2-128.pdf?da=1&id=211561&seq=0&mobile=no
