### ISSUE TITLE
Remeshing: L_max and L_min

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#28]
@ataiya Could you explain again how to get the relationship between L_max/L_min and L (slide 42)? I guess L is the average length of edges. What does the equation |L_max-L|=|0.5L_max-L| mean (actually I think this is the only thing I'm not yet clear)?

**Comment by taiya** [comment]
Did you see the handwritten notes? The derivation is there.

**Comment by xuzheng0927** [comment]
Ok, I see that. I haven't downloaded it to my laptop until a sec ago. I'll read it. Thanks.
