### ISSUE TITLE
Problem in constructing SparseMatrix

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#3]
I simply have:

`Eigen::SparseMatrix<double> G(cloud.n_vertices(), cloud.n_vertices());`

When I ran make, I got:

`error: no template named
      'SparseMatrix' in namespace 'Eigen'; did you mean 'SparseMatrixBase'?`

Is the Eigen library in the repo an old version?

**Comment by nlguillemot** [comment]
Eigen isn't in the repo, it's a third-party dependency that you install yourself. Maybe you just need to include a header, like `#include <Eigen/Sparse>`

```
https://github.com/ataiya/dgp/wiki/Compiling-in-Ubuntu-15.04
https://github.com/ataiya/dgp/wiki/Compiling-in-OSX
```

**Comment by xuzheng0927** [comment]
Yeah I am able to construct it now. Closing the issue.
