### ISSUE TITLE
GLFW3_LIBRARIES. What is this?

### ISSUE THREAD

**Issue by ShovelHand** [ataiya/dgp#3]
When using CMakeGui, what should we put in the GLFW3_LIBRARIES field? I tried the same thing I used for GLFW3_INCLUDE_DIRS, but the compiler was not happy about it. I'm not sure if I have to set up these libraries separately or what.

**Comment by marovira** [comment]
@ShovelHand I'm assuming that you downloaded the Windows binaries for GLFW? If so, in the same directory where you have the include folder there should be another one that says lib-vc20**. In there are the .lib files that you need for GLFW. Just select the one corresponding to your IDE and that should fix your issue.

**Comment by ataiya** [comment]
@marovira let's update the compile instructions once this is fixed ;)

**Comment by ShovelHand** [comment]
Ok, I must have downloaded the wrong thing.
