### ISSUE TITLE
Multiscale deformation algorithm in real-time

### ISSUE THREAD

**Issue by alinachin** [ataiya/dgp#31]
Would it be a reasonable approach to keep the base (smoothed) mesh in memory and apply the deformation & high-frequency details every step? Essentially, separating the low and high frequencies only during the initialization, not for every frame.

I've been reading the textbook and the slides and they present the multiscale deformation process as one deformation, whereas the assignment is to make an interactive app, so a series of deformations. I looked for similar papers and implementations but didn't have any luck apart from [Zorin 1997], which seems similar to what I'm suggesting, but I'm not confident yet.

**Comment by taiya** [comment]
It's not the smoothed mesh that remains in memory, it's the sparse factorized laplacian matrices that are! If I recall correctly, you missed the lecture when we covered a pre-factorized deformation algorithm -- ask your colleagues as that exercise's solution is not public (as it is part of Hw3).

**Comment by alinachin** [comment]
No, I caught up on the MATLAB exercise earlier; my question was me overthinking this process:

![multiresolution](https://cloud.githubusercontent.com/assets/415788/20998758/044af4c0-bcc5-11e6-92a9-3b25444f59d1.png)

So what you're saying is the decomposition, editing, and reconstruction are performed each time we need to deform the mesh?

**Comment by taiya** [comment]
The decomposition and the factorization of B (so that the low frequency is edited efficiently Is done in pre-processing. The solve through back-substitution and the reconstruction of details is done per-frame

**Comment by alinachin** [comment]
Thank you, that clears things up!
