### ISSUE TITLE
What is the RBF center of a generic point x?

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#4]
Is that the centroid of k-sized neighbourhood?

**Comment by xuzheng0927** [comment]
Regarding to these descriptions: "the offset distance should be determined according to the bounding box diagonal length" and "the rows [N: 2N-1] are the basis functions of offset points". What are the "offset points" and the "bounding box diagonal length"? Will they be covered by the lectures?

**Comment by taiya** [comment]
We didn't get to RBF in the last lecture.
It will be covered tomorrow in class.
