### ISSUE TITLE
RBF implicit function

### ISSUE THREAD

**Issue by xuzheng0927** [ataiya/dgp#5]
I implemented the RBF part and it works perfect for the sphere obj, but not as expected on the face obj (while Hoppe works well on the face). So I wonder if I misunderstood something. Are the centers: (1) the cloud points, (2) the cloud points plus epsilon*(their normal values)? If this is correct, what could be the reason? Should I change epsilon?

**Comment by taiya** [comment]
Yes, you have to play with the parameter and find something that works.
I recommend to play on a 2D example in Matlab to better understand the problem

**Comment by xuzheng0927** [comment]
ok
