### ISSUE TITLE
Assignment 2 Clarification

### ISSUE THREAD

**Issue by leonsenft** [ataiya/dgp#7]
For halfedge collapse and checking collapse legality, the comments in the provided code suggest looking at the `OpenGP::SurfaceMesh` documentation. I noticed SurfaceMesh implements `collapse` and `is_collapse_ok` methods. At first I figured the comments implied we should use these methods in our implementation, but it seems like these methods accomplish everything we've been assigned to do.

Is my assumption correct that we can't use these methods and need to implement them ourselves? If that's the case, to what extent can we make use of the methods that `is_collapse_ok` calls internally (such as `is_boundary`)?

Thanks!

**Comment by ataiya** [comment]
You can surely use those methods, that's why I pointed you to the documentation :)
Indeed the boundary and manifold test functions are provided by the library.

What requires a bit more work is ```/// TASK: check for face foldovers```

**Comment by leonsenft** [comment]
Awesome, thanks for making that clear!
