### ISSUE TITLE
VSA question

### ISSUE THREAD

**Issue by shengyangwei** [ataiya/dgp#8]
For the extra requirement for ELEC 586, I'm not clear about the L22
metric, when reading Cohen-Steiner's paper and the textbook, I only find
the L21 and L2 metric, so could you please provide more information about
it. And is the planar primitive phase same as the geometry partitioning in
the paper? I mean whether do I only need to implement face clustering and
proxy fitting?

Another thing is that do I need to output the geometry partitioning result
to the window? I think it is really hard. Or just provide the complied cpp
sourcefile?

**Comment by ataiya** [comment]
L22 is L_2^2 is what you call "L2" and what you find in the paper. 

VSA has 2 phases:
- The first is computing the proxies given a point set
- The second is computing the clusters that are associated to that proxy

I am not sure what is unclear, just the name that has been given to the phases?

You can create a simple mesh that is nothing but a union of planar polygons. 
What I ask is what you see at the center of Figure 1 in the paper.
